version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: postgres_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - /pgdata:/data/postgres
    networks:
      - rentx_network
  app:
    image: 'node:latest'
    container_name: rentx
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ../:/usr/src/app
    depends_on:
      - database_ignite
    working_dir: /usr/src/app
    command: bash -c "yarn && yarn dev"
    networks:
      - rentx_network

networks:
  rentx_network:
    driver: bridge
